services:
  backend:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ../
      dockerfile: docker/vue/Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
