services:
  backend:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:80"
    working_dir: /var/www/html
    volumes:
      - ../backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'backend_api'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ../
      dockerfile: docker/vue/Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
